config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'

  resources :storages do
    resources :reservations, only: %i[create new]
  end

  # resources :users do
  #   resources :storages
  # end

  resources :reservations, only: %i[index show edit destroy update]

  get '/user_page', to: 'pages#user_page'
  get 'users/:id/storages', to: 'storages#user_storages', :as => :user_storages

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reservations
  has_many :storages
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password, presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :html, :json

  def create
    build_resource(sign_up_params)
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def storages
    if params[:user_id]
      @storages = User.find(params[:user_id]).storages
    else
      @storages = Storage.all
    end
  end
end

app/views/users/storages.html.erb
<div class="user-dashboard">

  <%= render "shared/sidebar" %>

  <div class="user-right-container">
    <div>
      <h1>My Storages</h1>
      <div>
        <% current_user.storages.each do |storage| %>

          <div class="my-storages-card">
            <div>
              <img src="https://images.unsplash.com/photo-1522050212171-61b01dd24579?ixlib=rb-1.2.1ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=formatfit=crop&w=880&q=80" alt="storage" class="index-storage-img">
            </div>
            <div class="my-storages-items">
              <div class="my-storages-item">
                <p>Title:</p>
                <p class="item-input"><%= storage.title %></p>
              </div>
              <div class="my-storages-item">
                <p>Description:</p>
                <p class="item-input"><%= storage.description %></p>
              </div>
              <div class="my-storages-item">
                <p>Address:</p>
                <p class="item-input"><%= storage.address %></p>
              </div>
              <div class="my-storages-item">
                <p>Meters:</p>
                <p class="item-input"><%= storage.meters %>m<sup>2</sup></p>
              </div>
              <div class="my-storages-bottom">
                <div class="my-storages-item">
                  <p>City:</p>
                  <p class="item-input"><%= storage.city %></p>
                </div>
                <div class="my-storages-item">
                  <p>Country:</p>
                  <p class="item-input"><%= storage.country %></p>
                </div>
                <div class="my-storages-item">
                  <p>Price:</p>
                  <p class="item-input">$<%= storage.price %></p>
                </div>
                <div class="my-storages-item">
                  <p>Type:</p>
                  <p class="item-input"><%= storage.type %></p>
                </div>
              </div>
              <div class="my-storages-controls">
                <p><%= link_to "Edit", edit_storage_path %></p>
                <p><%= link_to 'Delete', storage_path(@storages),style:"font-size:15px;", method: :delete, data: {confirm: "Are you sure you want to delete this storage?"}%></p>
              </div>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  </div>

</div>