config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'

  resources :storages do
    resources :reservations, only: %i[create new]
  end

  # resources :users do
  #   resources :storages
  # end

  resources :reservations, only: %i[index show edit destroy update]

  get '/user_page', to: 'pages#user_page'
  get 'users/:id/storages', to: 'storages#user_storages', :as => :user_storages

end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-outline-light rounded-circle btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i></a>

      <!-- Twitter -->
      <a class="btn btn-outline-light rounded-circle btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i></a>

      <!-- Google -->
      <a class="btn btn-outline-light rounded-circle btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i></a>

      <!-- Instagram -->
      <a class="btn btn-outline-light rounded-circle btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i></a>

      <!-- Linkedin -->
      <a class="btn btn-outline-light rounded-circle btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i></a>

    </section>
    <!-- Section: Social media -->

    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Storage Types</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="/storages?query=car+parking&commit=Search" class="text-white">Car Parking</a>
            </li>
            <li>
              <a href="/storages?query=rv&commit=Search" class="text-white">RV</a>
            </li>
            <li>
              <a href="/storages?query=business+inventory&commit=Search" class="text-white">Business Inventory</a>
            </li>
            <li>
              <a href="/storages?query=furniture&commit=Search" class="text-white">Furniture</a>
            </li>
            <li>
              <a href="/storages?query=boats&commit=Search" class="text-white">Boats</a>
            </li>
            <li>
              <a href="/storages?query=personal+storage&commit=Search" class="text-white">Personal Storage</a>
            </li>
            <li>
              <a href="/storages?query=storage+unit&commit=Search" class="text-white">Storage Unit</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Main Cities</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="/storages?query=london&commit=Search" class="text-white">London</a>
            </li>
            <li>
              <a href="/storages?query=paris&commit=Search" class="text-white">Paris</a>
            </li>
            <li>
              <a href="/storages?query=barcelona&commit=Search" class="text-white">Barcelona</a>
            </li>
            <li>
              <a href="/storages?query=amsterdam&commit=Search" class="text-white">Amsterdam</a>
            </li>
            <li>
              <a href="/storages?query=lisbon&commit=Search" class="text-white">Lisbon</a>
            </li>
            <li>
              <a href="/storages?query=berlin&commit=Search" class="text-white">Berlin</a>
            </li>
            <li>
              <a href="/storages?query=brussels&commit=Search" class="text-white">Brussels</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Countries</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="/storages?query=united+kingdom&commit=Search" class="text-white">United Kingdom</a>
            </li>
            <li>
              <a href="/storages?query=france&commit=Search" class="text-white">France</a>
            </li>
            <li>
              <a href="/storages?query=spain&commit=Search" class="text-white">Spain</a>
            </li>
            <li>
              <a href="/storages?query=the+netherlands&commit=Search" class="text-white">The Netherlands</a>
            </li>
            <li>
              <a href="/storages?query=portugal&commit=Search" class="text-white">Portugal</a>
            </li>
            <li>
              <a href="/storages?query=germany&commit=Search" class="text-white">Germany</a>
            </li>
            <li>
              <a href="/storages?query=belgium&commit=Search" class="text-white">Belgium</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Storage Features</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="/storages?query=smoke+detector&commit=Search" class="text-white">Smoke Detector</a>
            </li>
            <li>
              <a href="/storages?query=security+camera&commit=Search" class="text-white">Security Camera</a>
            </li>
            <li>
              <a href="/storages?query=pet+free&commit=Search" class="text-white">Pet Free</a>
            </li>
            <li>
              <a href="/storages?query=climate+controlled&commit=Search" class="text-white">Climate Controlled</a>
            </li>
            <li>
              <a href="/storages?query=locked+area&commit=Search" class="text-white">Locked Area</a>
            </li>
            <li>
              <a href="/storages?query=open+space&commit=Search" class="text-white">Open Space</a>
            </li>
            <li>
              <a href="/storages?query=closed+space&commit=Search" class="text-white">Closed Space</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-white" href="#">STORAGES</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="navbar-container container-fluid">
    <div>
      <%= link_to "STORAGES", root_path , class: "navbar-brand" %>
    </div>
    <button class="navbar-toggler mb-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path , class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Storages", storages_path , class: "nav-link text-white" %>
        </li>
      </ul>

      <% if current_user %>
      <div>
        <%= link_to "Become Host", new_storage_path, :class => "btn btn-primary py-2 px-3" %>
      </div>
      <% else %>
      <div>
        <%= link_to "Become Host", new_user_session_path, :class => "btn btn-primary py-2 px-3" %>
      </div>
      <% end  %>

      <div>
        <% if current_user %>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <div class="avatar-account">
              <img src="/avatar.png" alt="avatar" class="avatar-nav">
              <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.first_name %> <%= current_user.last_name.first %>.
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Account", user_page_path, class: "dropdown-item" %></li></li>
                <li><%= link_to "My Storages", user_storages_path(current_user), class: "dropdown-item" %></li>
                <li><%= link_to "My Reservations", reservations_path, class: "dropdown-item" %> </li>
              </ul>
            </div>
          </li>
          <li class="nav-item active">
            <%= link_to "Sign Out", destroy_user_session_path, class: "nav-link text-white", method: :delete %>
          </li>
          <% else %>
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to "Log In", new_user_session_path , class: "nav-link btn-primary login-btn text-white" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Sign Up", new_user_registration_path , class: "nav-link text-white" %>
            </li>
          <% end %>
          </ul>
        </ul>
      </div>

    </div>
  </div>
</nav>

app/views/shared/_sidebar.erb
  <div class="user-left-container">
    <h3>My Account</h3>
    <ul class="dashboard-list">
      <li><%= link_to "Personal Information", user_page_path %></li>
      <li><%= link_to "My Storages", user_storages_path(current_user) %></li>
      <li><%= link_to "My Reservations", reservations_path %> </li>
    </ul>
  </div>