config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'

  resources :storages do
    resources :reservations, only: %i[create new]
  end

  # resources :users do
  #   resources :storages
  # end

  resources :reservations, only: %i[index show edit destroy update]

  get '/user_page', to: 'pages#user_page'
  get 'users/:id/storages', to: 'storages#user_storages', :as => :user_storages

end

app/views/pages/home.html.erb
<div>
<%# --------- HERO ----------- %>
  <div class="home-hero">
    <div class="hero-container">
      <div class="hero-header">
        <h2 style="font-size:3rem">Find the perfect place</h2>
        <h2 style="font-size:3rem">for your <span class="typewriter"> </span></h2>
        <script>
          var typed = new Typed(".typewriter",{
          strings: ["car","boat","boxes", "inventory", "furniture", "RV"] ,
          typeSpeed: 100,
          backSpeed: 100,
          loop: true,
          showCursor: false
          })
      </script>
      </div>
      <%# --------- SEARCH BAR ----------- %>
      <%= form_tag storages_path, method: :get, class: 'home-search-container' do %>
        <div class="home-search-form">
          <%= text_field_tag :query,
          params[:query],
          placeholder: "Search for a city...",
          class: 'home-search-bar'
          %>
          <%= submit_tag("Search", :class=>"home-search-btn btn-primary") %>
        </div>
      <% end %>
    </div>
  </div>

<%# ---------- STORAGES TYPES ------------  %>
<div class="home-storages-container">
  <h2 class="storages-header mb-5 mt-5" style="font-size:3rem">There is a storage for everything...</h2>
  <div class="home-cards-grid">
      <div class="home-card">
        <a href="/storages?query=business+inventory&commit=Search">
          <img src="inventory.jpg" class="home-card-img-top" alt="...">
          <p class="card-text">Business Inventory</p>
        </a>
      </div>
      <div class="home-card">
        <a href="/storages?query=car+parking&commit=Search">
          <img src="car-garage.jpg" class="home-card-img-top" alt="...">
          <p class="card-text">Car Parking</p>
        </a>
      </div>
      <div class="home-card">
        <a href="/storages?query=boats&commit=Search">
          <img src="boats.jpg" class="home-card-img-top" alt="...">
          <p class="card-text">Boats</p>
        </a>
      </div>
      <div class="home-card">
        <a href="/storages?query=rv&commit=Search">
          <img src="rv.jpg" class="home-card-img-top" alt="...">
          <p class="card-text">RV</p>
        </a>
      </div>
      <div class="home-card">
        <a href="/storages?query=personal&commit=Search">
          <img src="personal.jpg" class="home-card-img-top" alt="...">
          <p class="card-text">Personal</p>
        </a>
      </div>
      <div class="home-card">
        <a href="/storages?query=furniture&commit=Search">
          <img src="furniture.jpg" class="home-card-img-top" alt="...">
          <p class="card-text">Furniture</p>
        </a>
      </div>
  </div>
</div>

<%#--------WHY RENT STORAGE----------%>
  <div class="container text-center">
    <h2 class="mb-5 mt-5" style="font-size:3rem"> Why rent a storage with us? </h2>
    <div class="row why-storage-container">
      <div class="col-6 col-md-3 why-storage">
        <img src="reservation.png" alt="reservation-icon" class="mb-2">
        <h4 class="title">Easy reservation</h4>
        <p class="description">With a few clicks find and reserve a suitable storage for your items.</p>
      </div>
      <div class="col-6 col-md-3 why-storage">
        <img src="open-box.png" alt="open-box-icon" class="mb-2">
        <h4 class="title">Box it up</h4>
        <p class="description">Pack your items in an easy way and take them to your nearby storage.</p>
      </div>
      <div class="col-6 col-md-3 why-storage">
        <img src="warehouse.png" alt="warehouse-icon" class="mb-2">
        <h4 class="title">Organize yourself</h4>
        <p class="description">Once in the storage, arrange your items in your own way. </p>
      </div>
      <div class="col-6 col-md-3 why-storage">
        <img src="garage.png" alt="garage-icon" class="mb-2">
        <h4 class="title">Car suitable spaces</h4>
        <p class="description">You can find the perfect parking space for your car.</p>
      </div>
    </div>
  </div>

<%#--------DISCOVER STORAGES-------------%>

  <div class="discover-storages-container text-center">
    <h2 class="discover-storages-header mb-5 mt-5" style="font-size:3rem">Discover storages</h2>
    <div class="discover-storages-cards">
      <% Storage.all.sample(4).each do |storage| %>
        <%= link_to storage_path(storage) do %>
          <div class="discover-storages-card" >
            <div class="discover-storages-img">
              <% if storage.photos.attached? %>
                <%= cl_image_tag storage.photos[0].key, class:"show-storage-near-img" %>
              <% else %>
                <img src="/noimage.png" alt="no-image" class="show-storage-near-img">
              <% end %>
              <p class="discover-storages-price">$<%= storage.price.to_i %><b style="font-size: 12px">/day</b></p>
            </div>
            <div class="discover-storages-details">
              <p class="discover-storages-title"><strong><%= storage.title.truncate(24).capitalize%></strong></p>
              <p class="discover-storages-type"> <%=storage.storage_type%> - <%=storage.meters%>m<sup>2</sup></p>
              <p class="discover-storages-user">
                <i class="fa-solid fa-user"></i>
                <%=storage.user.first_name%>
                <%=storage.user.last_name.first%>.
              </p>
              <p class="discover-storages-city">
                <i class="fa-solid fa-location-dot"></i>
                <%= storage.city%>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="home-see-more-container mt-5">
      <%= link_to "See More", storages_path, :class => "btn btn-primary btn-lg btn-block py-2 px-3" %>
    </div>
  </div>


<%#--------BECOME A HOST-----------%>
  <div class="become-host-container mt-5 mb-4 text-center">
    <h2 class="become-host-header mb-5 mt-5">Rent your space. Become a host!</h2>
    <div class="host-container">
      <%# <button class="host-btn", storages_path> Become Host </button> %>
      <%= link_to "Become Host", new_storage_path, :class => "btn btn-primary btn-lg btn-block py-2 px-3" %>
    </div>
  </div>

</div>

app/views/pages/user_page.erb
<div class="user-dashboard">

  <%= render 'shared/sidebar' %>

  <div class="user-right-container">
  <div class="user-information-container">
    <div class="avatar-container">
      <img src="avatar.png" alt="avatar" class="account-avatar">
    </div>
    <div class="personal-information">
      <div class="personal-info-header">
        <h1>Personal Information</h1>
        <%= link_to edit_user_registration_path do %>
          <i class="fa-solid fa-pen-to-square"></i>
        <% end %>
      </div>
      <div><strong>First Name:</strong> <%= current_user.first_name %></div>
      <div><strong>Last Name:</strong> <%= current_user.last_name %></div>
      <div><strong>Email:</strong> <%= current_user.email %></div>
      <div><strong>Document Number:</strong> <%= current_user.document_number %></div>
      <div><strong>User since:</strong> <%= current_user.created_at.to_formatted_s(:long_ordinal) %></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>

  </div>

</div>